import {useState} from 'react';
import {gpsStartCoordinate} from '../lib/gpsStart.js';
import { remainingTrip } from '../lib/gpsProgress.js';
export default function GpsPanel({gps,route,mode,editor,onLocate}) {
  const [message,setMessage]=useState('');
  const useStart=()=>{try{const coordinate=gpsStartCoordinate(gps.fix);if(editor.update(null,'move',0,coordinate)){onLocate(coordinate);setMessage('Titik awal memakai posisi Anda. Kedua rute dihitung ulang.');}}catch(error){setMessage(error.message);}};
  const progress=remainingTrip(route,gps.fix,mode,gps.now);
  const messages={ambiguous:'Posisi dekat persilangan atau rute berulang. Sisa perjalanan belum dapat dipastikan.',waiting:'Menunggu lokasi dan rute terpilih.',stale:'Lokasi sudah lebih dari 30 detik. Menunggu pembaruan GPS.',inaccurate:'Akurasi GPS belum cukup (lebih dari 50 m).', 'off-route':'Anda berada di luar rute terpilih. Perbarui titik perjalanan secara manual.',arrived:'Anda berada dekat tujuan pada jaringan jalan.'};
  return <section className="routing-status" aria-label="Pelacakan GPS"><strong>Sisa perjalanan</strong><p>Pelacakan diproses di browser. Jika dipakai sebagai titik awal, koordinat dikirim ke backend routing; saat traffic aktif, titik perjalanan juga dikirim ke TomTom.</p><button className="retry-button" onClick={gps.enabled ? gps.stop : gps.start}>{gps.enabled ? 'Hentikan GPS' : 'Aktifkan GPS'}</button><button className="retry-button" onClick={useStart} disabled={!gps.enabled || !gps.fix}>Gunakan lokasi saya sebagai awal</button><div aria-live="polite">{message && <p>{message}</p>}{gps.error && <p>{gps.error}</p>}{gps.enabled && <><p>{progress.status==='tracking' ? `Sisa ${progress.remainingMeters} m · ${progress.minutes == null ? 'Sedang berhenti; estimasi waktu ditunda' : `sekitar ${progress.minutes} menit`}` : messages[progress.status]}</p>{progress.status==='tracking' && <p>{progress.speedSource==='gps' ? 'Waktu memakai kecepatan GPS saat ini.' : progress.speedSource==='model' ? 'Kecepatan GPS belum tersedia; memakai estimasi moda.' : 'Kecepatan GPS di bawah 0,5 m/detik.'} Belum termasuk kemacetan mendatang atau akses dari ujung rute ke pin.</p>}{gps.fix && <p>Akurasi ±{Math.round(gps.fix.accuracy)} m · pembaruan {new Date(gps.fix.timestamp).toLocaleTimeString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p>}</>}</div></section>;
}
